name: "Build and Test"
description: "Uses Yarn to install dependencies, build artifact and run tests."

runs:
  steps:
    - name: "Install, Build, Test"
      run: |
        yarn install
        yarn build
        yarn test
      shell: bash
