name: "Build and Test"
description: "Uses Yarn to install dependencies, build artifact and run tests."

on: push
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "15.x"
      - name: "Install, Build, Test"
        run: |
          yarn install
          yarn build
          yarn test
        shell: bash
        