name: "Deploy with AWS CDK"
on: 
  push: 
    branches: [ trunk ]
jobs:
  deploy-cdk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "15.x"
      - uses: .github/actions/build-and-test

      - name: Install CDK Dependencies 
        run: yarn install
        shell: bash
        working-directory: ./cdk

      - name: cdk diff
        uses: youyo/aws-cdk-github-actions@v1
        with:
          cdk_subcommand: 'diff'
          actions_comment: true
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-2'

        # - name: cdk synth
        #   uses: youyo/aws-cdk-github-actions@v1
        #   working-directory: ./cdk
        #   with:
        #     cdk_subcommand: 'synth'
        #     cdk_version: '1.93.0'
        #   env:
        #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        #     AWS_DEFAULT_REGION: 'us-east-2'

        # - name: cdk deploy
        #   uses: youyo/aws-cdk-github-actions@v1
        #   working-directory: ./cdk
        #   with:
        #     cdk_subcommand: 'deploy'
        #     cdk_stack: 'CdkStack'
        #     actions_comment: false
        #     args: '--require-approval never'
        #   env:
        #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        #     AWS_DEFAULT_REGION: 'us-east-2'
