name: "Deploy with AWS CDK"
on: 
  push: 
    branches: [ trunk ]
jobs:
  deploy-cdk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "15.x"
      - uses: ./.github/actions/build-and-test

      # - name: Install CDK Dependencies 
      #   run: yarn install
      #   shell: bash
      #   working-directory: ./cdk
      # I'm gonna circle around to tackling deployments later
      # I don't have the sanity to debug github actions 
