name: Test on Pull Request
on: 
  pull_request:
    branches: [ trunk ]
  workflow_dispatch:
jobs:
  test-on-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/build-and-test
        