name: Test on Pull Request
on: 
  pull_request:
    branches: [ $default-branch ]
  jobs:
    test-on-pr:
      runs-on: ubuntu-latest
      steps:
        - name: Build and Test
          uses: ./.github/actions/build-and-test
        